GAME_RECORDS_PATH=records/games
PLAYER_RECORDS_PATH=records/players
ROOMS_RECORDS_PATH=records/rooms
PENDING_RECORDS_PATH=records/pending
ALLOWED_ORIGINS=http://127.0.0.1:5500

CASSANDRA_IP=172.31.9.25
CASSANDRA_PORT=9042
CASSANDRA_DATACENTER=datacenter1
CASSANDRA_KEYSPACE=batch1_2026_trainees

ROOM_TABLE=soto_room_table
GAME_TABLE=soto_game_table
PLAYER_TABLE=soto_player_table
